#!/usr/bin/env python3
"""Validate a career-os career workspace.

Checks the conventions in workspace-conventions.md that a script can check
deterministically: frontmatter, evidence IDs, proof maps, numbers in
outward-facing assets, the "Not claimed" absence list, unapproved
suggestions, the changelog, and staleness.

Usage:
  validate_workspace.py [WORKSPACE] [--file PATH] [--stale] [--today YYYY-MM-DD]
  validate_workspace.py --hook      # Claude Code PostToolUse hook; reads JSON on stdin

Exit codes: 0 clean (warnings allowed), 1 errors, 2 errors in --hook mode.
Standard library only; Python 3.9+.

Canonical copy: plugins/career-os/shared/validate_workspace.py. The copies in
skills/*/scripts/ are generated by scripts/sync_shared.py; edit the canonical one.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

AREAS = ["ground-truth", "interests", "portfolio", "titles", "positioning", "decisions"]
EXEMPT_FILES = {"README.md", "changelog.md"}
REQUIRED_KEYS = ["title", "type", "status", "last_updated", "open_questions"]
TYPES = {"ground-truth", "interest", "portfolio", "title", "positioning", "index", "decision"}
STATUSES = {"complete", "partial", "draft", "not_started", "archived"}
SENSITIVITIES = {"public", "private", "restricted"}
# Default days before a file counts as stale, by `type`. `review_after` overrides.
STALE_DAYS = {
    "ground-truth": 180,
    "portfolio": 180,
    "title": 180,
    "positioning": 120,
    "interest": 365,
    "decision": 90,
    "index": 180,
}

EV_ID = re.compile(r"(?<![\w-])EV-\d{3,}(?!\d)")
EV_DEF = re.compile(r"^###\s+(EV-\d{3,})\b")
HEADING = re.compile(r"^(#{1,6})\s+(.*)$")
TAG = re.compile(
    r"\[(?:stated|source:[^\]]+|researched:[^\]]+|suggested\s*(?:→|->)\s*approved)\]",
    re.IGNORECASE,
)
BARE_SUGGESTED = re.compile(r"\[suggested\]", re.IGNORECASE)
MD_LINK = re.compile(r"\]\([^)]+\)")
URL = re.compile(r"https?://\S+")
NUMBER = re.compile(
    r"(?<![\w.,/-])(\$|€|£)?(\d[\d,]*(?:\.\d+)?)"
    r"(\s?(?:%|x|×|k|K|M|B|bn|million|billion|thousand)(?![A-Za-z]))?"
)
WORKSPACE_TITLE = re.compile(r"^#\s+Career Workspace", re.MULTILINE)
SKIP_ABSENCE_SECTIONS = ("not for", "retired", "rejected", "not claimed")


@dataclass
class Finding:
    level: str  # "ERROR" or "WARN"
    code: str
    path: str
    line: int
    message: str

    def render(self) -> str:
        loc = f"{self.path}:{self.line}" if self.line else self.path
        return f"{self.level} {self.code} {loc} {self.message}"


@dataclass
class Doc:
    rel: str
    path: Path
    lines: list
    meta: dict
    body_start: int  # 0-based index of first body line
    fm_error: str | None


# ---------------------------------------------------------------- parsing


def parse_frontmatter(lines: list) -> tuple[dict, int, str | None]:
    """Parse the small YAML subset the workspace uses.

    Supports `key: value`, `key: [a, b]`, `key:` followed by `- item` lines,
    and block scalars (`key: |`), which are kept as raw text.
    """
    if not lines or lines[0].strip() != "---":
        return {}, 0, "missing frontmatter (file must start with ---)"
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return {}, 0, "frontmatter is not closed with ---"
    meta: dict = {}
    key = None
    for raw in lines[1:end]:
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        item = re.match(r"^\s+-\s*(.*)$", raw)
        if item and key is not None and isinstance(meta.get(key), list):
            meta[key].append(_scalar(item.group(1)))
            continue
        if raw.startswith((" ", "\t")) and key is not None:
            if isinstance(meta.get(key), str):
                meta[key] = (meta[key] + "\n" + raw.strip()).strip()
            continue
        kv = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", raw)
        if not kv:
            return meta, end + 1, f"cannot parse frontmatter line: {raw.strip()!r}"
        key, value = kv.group(1), kv.group(2).strip()
        if value == "":
            meta[key] = []
        elif value in ("|", ">", "|-", ">-"):
            meta[key] = ""
        elif value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            meta[key] = [_scalar(v) for v in _split_list(inner)] if inner else []
        else:
            meta[key] = _scalar(value)
    return meta, end + 1, None


def _split_list(inner: str) -> list:
    parts, depth, buf = [], 0, ""
    for ch in inner:
        if ch in "[{":
            depth += 1
        elif ch in "]}":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(buf)
            buf = ""
        else:
            buf += ch
    parts.append(buf)
    return [p.strip() for p in parts if p.strip()]


def _scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def load_doc(ws: Path, path: Path) -> Doc:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    if path.name in EXEMPT_FILES and path.parent == ws:
        return Doc(path.relative_to(ws).as_posix(), path, lines, {}, 0, None)
    meta, start, err = parse_frontmatter(lines)
    return Doc(path.relative_to(ws).as_posix(), path, lines, meta, start, err)


def sections(doc: Doc):
    """Yield (heading_text_lower, [(line_no, text), ...]) for each ##-or-deeper section."""
    current, buf = "", []
    for idx in range(doc.body_start, len(doc.lines)):
        line = doc.lines[idx]
        m = HEADING.match(line)
        if m and len(m.group(1)) == 2:
            yield current, buf
            current, buf = m.group(2).strip().lower(), []
        else:
            buf.append((idx + 1, line))
    yield current, buf


def section_lines(doc: Doc, name: str) -> list:
    name = name.lower()
    out = []
    for heading, lines in sections(doc):
        if heading.startswith(name):
            out.extend(lines)
    return out


def parse_date(value) -> dt.date | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        return dt.date.fromisoformat(value.strip())
    except ValueError:
        return None


def norm_number(raw: str) -> str:
    return raw.replace(",", "")


def numbers_in(text: str) -> list:
    """Return claim-like numbers in text, normalized (commas removed).

    Ignores bare years (1900-2099) and bare single digits; keeps anything with a
    currency sign or a unit suffix (%, x, k, M, million, ...).
    """
    text = URL.sub(" ", MD_LINK.sub("]", text))
    text = EV_ID.sub(" ", text)
    found = []
    for m in NUMBER.finditer(text):
        cur, num, suffix = m.group(1), m.group(2).rstrip(","), m.group(3)
        if not num:
            continue
        value = norm_number(num)
        if not cur and not suffix:
            digits = value.split(".")[0]
            if len(digits) < 2:
                continue
            if len(digits) == 4 and 1900 <= int(digits) <= 2099 and "." not in value:
                continue
        found.append(value)
    return found


# ---------------------------------------------------------------- workspace


def find_workspace(start: Path) -> Path | None:
    start = start.resolve()
    candidates = [start] + list(start.parents) if start.is_dir() else list(start.parents)
    for d in candidates:
        readme = d / "README.md"
        if d.name == "career-workspace" and d.is_dir():
            return d
        if readme.is_file():
            try:
                head = readme.read_text(encoding="utf-8", errors="replace")[:500]
            except OSError:
                continue
            if WORKSPACE_TITLE.search(head):
                return d
    return None


def workspace_docs(ws: Path) -> list:
    docs = []
    for name in ("README.md", "changelog.md"):
        if (ws / name).is_file():
            docs.append(load_doc(ws, ws / name))
    for area in AREAS:
        root = ws / area
        if root.is_dir():
            for p in sorted(root.rglob("*.md")):
                if any(part.startswith(".") for part in p.relative_to(ws).parts):
                    continue
                docs.append(load_doc(ws, p))
    return docs


# ---------------------------------------------------------------- checks


def check_frontmatter(doc: Doc, today: dt.date, out: list) -> None:
    if doc.rel in EXEMPT_FILES:
        return
    if doc.fm_error:
        out.append(Finding("ERROR", "E-FM", doc.rel, 1, doc.fm_error))
        return
    m = doc.meta
    for key in REQUIRED_KEYS:
        if key not in m:
            out.append(Finding("ERROR", "E-FM", doc.rel, 1, f"missing frontmatter key `{key}`"))
    if "type" in m and m["type"] not in TYPES:
        out.append(Finding("ERROR", "E-FM", doc.rel, 1,
                           f"type `{m['type']}` not one of {sorted(TYPES)}"))
    if "status" in m and m["status"] not in STATUSES:
        out.append(Finding("ERROR", "E-FM", doc.rel, 1,
                           f"status `{m['status']}` not one of {sorted(STATUSES)}"))
    if "sensitivity" in m and m["sensitivity"] not in SENSITIVITIES:
        out.append(Finding("ERROR", "E-FM", doc.rel, 1,
                           f"sensitivity `{m['sensitivity']}` not one of {sorted(SENSITIVITIES)}"))
    for key in ("last_updated", "review_after", "approved_on", "added"):
        if key not in m or m[key] in ("", []):
            continue
        d = parse_date(m[key])
        if d is None:
            out.append(Finding("ERROR", "E-FM", doc.rel, 1, f"`{key}` must be YYYY-MM-DD, got `{m[key]}`"))
        elif key != "review_after" and d > today:
            out.append(Finding("ERROR", "E-FM", doc.rel, 1, f"`{key}` {d} is in the future"))
    if "open_questions" in m and not isinstance(m["open_questions"], list):
        out.append(Finding("ERROR", "E-FM", doc.rel, 1, "`open_questions` must be a list"))
    if "derived_from" in m and not isinstance(m["derived_from"], list):
        out.append(Finding("ERROR", "E-FM", doc.rel, 1, "`derived_from` must be a list of EV IDs"))


def evidence_index(docs: list, out: list) -> dict:
    """Map EV ID -> text of its item in portfolio/evidence-inventory.md."""
    index: dict = {}
    first_line: dict = {}
    for doc in docs:
        if doc.rel != "portfolio/evidence-inventory.md":
            continue
        current = None
        for idx, line in enumerate(doc.lines):
            m = EV_DEF.match(line)
            if m:
                ev = m.group(1)
                if ev in index:
                    out.append(Finding("ERROR", "E-EV-DUP", doc.rel, idx + 1,
                                       f"{ev} is defined more than once (first at line {first_line[ev]}); "
                                       "EV IDs are never reused or renumbered"))
                    current = None
                    continue
                index[ev], first_line[ev], current = line, idx + 1, ev
            elif HEADING.match(line):
                current = None
            elif current:
                index[current] += "\n" + line
    return index


def check_ev_refs(docs: list, ev_index: dict, out: list) -> None:
    for doc in docs:
        derived = doc.meta.get("derived_from")
        if isinstance(derived, list):
            for ev in derived:
                if EV_ID.fullmatch(str(ev)) and ev not in ev_index:
                    out.append(Finding("ERROR", "E-EV-REF", doc.rel, 1,
                                       f"`derived_from` cites {ev}, which is not defined in "
                                       "portfolio/evidence-inventory.md"))
        for idx in range(doc.body_start, len(doc.lines)):
            line = doc.lines[idx]
            if doc.rel == "portfolio/evidence-inventory.md" and EV_DEF.match(line):
                continue
            for ev in EV_ID.findall(line):
                if ev not in ev_index:
                    out.append(Finding("ERROR", "E-EV-REF", doc.rel, idx + 1,
                                       f"{ev} is referenced but not defined in portfolio/evidence-inventory.md"))


def is_outward(doc: Doc) -> bool:
    if doc.rel == "titles/title-stack.md":
        return True
    return doc.rel.startswith("positioning/") and doc.rel != "positioning/experiments.md"


def needs_proof_map(doc: Doc) -> bool:
    return doc.rel.startswith("positioning/assets/") or doc.rel == "positioning/positioning.md"


def check_unapproved(doc: Doc, out: list) -> None:
    if not is_outward(doc):
        return
    for idx in range(doc.body_start, len(doc.lines)):
        if BARE_SUGGESTED.search(doc.lines[idx]):
            out.append(Finding("ERROR", "E-UNAPPROVED", doc.rel, idx + 1,
                               "unapproved `[suggested]` content in an outward-facing file; "
                               "get approval and tag `[suggested → approved]`, or remove it"))


def proof_map_rows(doc: Doc) -> list:
    rows = []
    for line_no, text in section_lines(doc, "proof map"):
        s = text.strip()
        if not s.startswith("|") or re.match(r"^\|[\s:|-]+\|?$", s):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if cells and cells[0].lower() in ("claim", "claims"):
            continue
        rows.append((line_no, s))
    return rows


def check_proof_map(doc: Doc, ev_index: dict, gt_text: str, out: list) -> None:
    if not needs_proof_map(doc) or doc.fm_error:
        return
    rows = proof_map_rows(doc)
    has_section = any(h.startswith("proof map") for h, _ in sections(doc))
    if not has_section:
        out.append(Finding("ERROR", "E-PROOF-MAP", doc.rel, 0,
                           "missing `## Proof map` section (| Claim | Evidence |)"))
        return
    for line_no, row in rows:
        if not (EV_ID.search(row) or TAG.search(row) or "](" in row):
            out.append(Finding("ERROR", "E-PROOF-MAP", doc.rel, line_no,
                               "proof-map row has no evidence (EV ID, workspace link, or provenance tag)"))

    for heading, lines in sections(doc):
        if heading.startswith("proof map"):
            continue
        for line_no, text in lines:
            if HEADING.match(text):
                continue
            for num in numbers_in(text):
                verdict = _number_supported(num, rows, ev_index, gt_text)
                if verdict:
                    out.append(Finding("ERROR", "E-NUMBER", doc.rel, line_no,
                                       f"`{num}` {verdict}"))


def _number_supported(num: str, rows: list, ev_index: dict, gt_text: str) -> str | None:
    """Return None if supported, else the reason it is not."""
    matching = [row for _, row in rows if num in numbers_in(row)]
    if not matching:
        return "is not in the proof map; add a row tracing it to evidence or remove it"
    if any(TAG.search(row) for row in matching):
        return None
    for row in matching:
        for ev in EV_ID.findall(row):
            if num in numbers_in(ev_index.get(ev, "")):
                return None
    if num in numbers_in(gt_text):
        return None
    return "appears in the proof map, but none of the cited evidence contains it"


def absence_terms(docs: list) -> list:
    terms = []
    for doc in docs:
        if not doc.rel.startswith("ground-truth/"):
            continue
        for line_no, text in section_lines(doc, "not claimed"):
            m = re.match(r"^\s*[-*]\s+(.*)$", text)
            if not m:
                continue
            term = re.split(r":|\s\(|\s-\s|\s–\s|\s—\s", m.group(1), maxsplit=1)[0]
            term = term.strip().strip("*`_ ").strip()
            if len(term) >= 2 and not term.startswith("_Not yet"):
                terms.append((term, doc.rel, line_no))
    return terms


def check_absence(docs: list, terms: list, out: list) -> None:
    if not terms:
        return
    patterns = [(t, src, re.compile(r"(?<!\w)" + re.escape(t) + r"(?!\w)", re.IGNORECASE))
                for t, src, _ in terms]
    for doc in docs:
        if not is_outward(doc):
            continue
        for heading, lines in sections(doc):
            if any(heading.startswith(s) for s in SKIP_ABSENCE_SECTIONS):
                continue
            for line_no, text in lines:
                for term, src, pat in patterns:
                    if pat.search(text):
                        out.append(Finding("ERROR", "E-ABSENCE", doc.rel, line_no,
                                           f"mentions `{term}`, which the user listed under "
                                           f"`## Not claimed` in {src}"))


def check_changelog(docs: list, ws: Path, today: dt.date, out: list) -> None:
    touched = [d.rel for d in docs
               if d.rel not in EXEMPT_FILES and parse_date(d.meta.get("last_updated")) == today]
    if not touched:
        return
    log = ws / "changelog.md"
    text = log.read_text(encoding="utf-8", errors="replace") if log.is_file() else ""
    if not re.search(rf"^\s*-\s*{today.isoformat()}\b", text, re.MULTILINE):
        out.append(Finding("ERROR", "E-CHANGELOG", "changelog.md", 0,
                           f"{len(touched)} file(s) updated {today} (e.g. {touched[0]}) "
                           f"but no `- {today} [skill]: ...` line"))


def check_readme(docs: list, ws: Path, out: list) -> None:
    readme = ws / "README.md"
    if not readme.is_file():
        out.append(Finding("WARN", "W-README", "README.md", 0, "workspace README.md is missing"))
        return
    text = readme.read_text(encoding="utf-8", errors="replace")
    for area in AREAS:
        if (ws / area).is_dir() and f"{area}/" not in text:
            out.append(Finding("WARN", "W-README", "README.md", 0,
                               f"no status row for `{area}/`"))


def check_stale(doc: Doc, today: dt.date, out: list, show_questions: bool) -> None:
    if doc.rel in EXEMPT_FILES or doc.fm_error:
        return
    m = doc.meta
    review = parse_date(m.get("review_after"))
    updated = parse_date(m.get("last_updated"))
    if m.get("status") == "archived":
        return
    if review and review < today:
        out.append(Finding("WARN", "W-STALE", doc.rel, 0, f"review_after {review} has passed"))
    elif not review and updated and m.get("type") in STALE_DAYS:
        age = (today - updated).days
        if age > STALE_DAYS[m["type"]]:
            out.append(Finding("WARN", "W-STALE", doc.rel, 0,
                               f"last updated {age} days ago (default for {m['type']}: "
                               f"{STALE_DAYS[m['type']]}); confirm it is still true"))
    if show_questions:
        for q in m.get("open_questions") or []:
            out.append(Finding("WARN", "W-OPEN", doc.rel, 0, f"open question: {q}"))


# ---------------------------------------------------------------- driver


def validate(ws: Path, today: dt.date, full: bool = True, show_questions: bool = False) -> list:
    out: list = []
    docs = workspace_docs(ws)
    for doc in docs:
        check_frontmatter(doc, today, out)
    ev_index = evidence_index(docs, out)
    check_ev_refs(docs, ev_index, out)
    gt_text = "\n".join("\n".join(d.lines) for d in docs if d.rel.startswith("ground-truth/"))
    for doc in docs:
        check_unapproved(doc, out)
        check_proof_map(doc, ev_index, gt_text, out)
        check_stale(doc, today, out, show_questions)
    check_absence(docs, absence_terms(docs), out)
    check_readme(docs, ws, out)
    if full:
        check_changelog(docs, ws, today, out)
    return out


def relevant_to(finding: Finding, rel: str) -> bool:
    """Which findings a hook run reports for a write to `rel`."""
    if finding.level != "ERROR":
        return False
    if finding.path == rel or finding.code == "E-EV-DUP":
        return True
    if rel == "portfolio/evidence-inventory.md" and finding.code in ("E-EV-REF", "E-NUMBER"):
        return True
    if rel.startswith("ground-truth/") and finding.code in ("E-ABSENCE", "E-NUMBER"):
        return True
    return False


def run_hook(today: dt.date) -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0
    file_path = (payload.get("tool_input") or {}).get("file_path")
    if not file_path or not str(file_path).endswith(".md"):
        return 0
    path = Path(file_path)
    if not path.is_absolute():
        path = Path(payload.get("cwd") or ".") / path
    ws = find_workspace(path)
    if ws is None:
        return 0
    try:
        rel = path.resolve().relative_to(ws.resolve()).as_posix()
    except ValueError:
        return 0
    findings = [f for f in validate(ws, today, full=False) if relevant_to(f, rel)]
    if not findings:
        return 0
    print(f"career-os workspace check found {len(findings)} problem(s) after writing {rel} "
          f"(workspace: {ws}):", file=sys.stderr)
    for f in findings:
        print("  " + f.render(), file=sys.stderr)
    print("Fix these now; the rules are in references/workspace-conventions.md. "
          "Never resolve a finding by inventing evidence: ask the user.", file=sys.stderr)
    return 2


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("workspace", nargs="?", help="path to career-workspace/ (default: search upward)")
    ap.add_argument("--file", help="locate the workspace from this file")
    ap.add_argument("--hook", action="store_true", help="run as a Claude Code PostToolUse hook")
    ap.add_argument("--stale", action="store_true", help="also list open questions")
    ap.add_argument("--today", help="override today's date (YYYY-MM-DD), for tests")
    args = ap.parse_args(argv)
    today = dt.date.fromisoformat(args.today) if args.today else dt.date.today()

    if args.hook:
        return run_hook(today)

    if args.workspace:
        ws = Path(args.workspace)
        if not ws.is_dir():
            print(f"not a directory: {ws}", file=sys.stderr)
            return 1
    else:
        ws = find_workspace(Path(args.file) if args.file else Path.cwd())
        if ws is None:
            print("no career workspace found; pass its path", file=sys.stderr)
            return 1

    findings = validate(ws, today, full=True, show_questions=args.stale)
    errors = [f for f in findings if f.level == "ERROR"]
    for f in sorted(findings, key=lambda f: (f.level != "ERROR", f.path, f.line)):
        print(f.render())
    print(f"{len(errors)} error(s), {len(findings) - len(errors)} warning(s) in {ws}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
